source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
    gem 'cancancan'
    gem 'mysql2', '>= 0.3.13', '< 0.5'
    gem 'nested_form_fields'
    gem 'jquery-datatables-rails', '~> 3.3.0'
    gem 'execjs'
    gem 'devise'
    gem 'bootstrap_form'
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'foreigner'
    gem 'web-console', '~> 2.0'
    gem 'seed_dump'
    gem 'byebug'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]